### ISSUE TITLE
Error while downloading spaCy data

### ISSUE THREAD

**Issue by aleSuglia** [spacy-io/spaCy#268]
Hello,

I'm trying to install your library using pip on my Archlinux distribution using Python 3.5. I've used the command:
    
     sudo pip install spacy

in order to install the package. After that, according to the official documentation, I need to execute the command:

     sudo python -m spacy.en.download

What I got after it downloads all the data is:

```
archive.gz checksum/md5 OK
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/spacy/en/download.py", line 58, in <module>
    plac.call(main)
  File "/usr/lib/python3.5/site-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/usr/lib/python3.5/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/lib/python3.5/site-packages/spacy/en/download.py", line 42, in main
    package = sputnik.install(about.__name__, about.__version__, about.__default_model__)
  File "/usr/lib/python3.5/site-packages/sputnik/__init__.py", line 46, in install
    path = pool.install(archive)
  File "/usr/lib/python3.5/site-packages/sputnik/pool.py", line 42, in install
    (archive.size() / 1024 / 1024))
AttributeError: 'Archive' object has no attribute 'size'
```

I've already updated all the packages installed through pip. I've tried to uninstall and install spaCy again, but I get the same error. 

Could you please give me any suggestion?

Thank you in advance,
Alessandro

**Comment by henningpeters** [comment]
Thanks for catching this bug. I already found the problem and will create a patch.

The underlying problem though seems to be that there is not enough disk space available anymore.

**Comment by henningpeters** [comment]
I uploaded a new version of sputnik that should fix the exception and output a proper error message. Please run ```pip install -U spacy``` and try again.
