### ISSUE TITLE
Import Error while installing spacy

### ISSUE THREAD

**Issue by nltkcse** [spacy-io/spaCy#283]
Hi,

I am getting following error while installing spacy. Kindly help.

user@user-lap:~$ sudo pip install spacy
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 37, in <module>
    import email.parser
  File "/usr/lib/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/usr/lib/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/usr/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/usr/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/usr/lib/python2.7/email/utils.py", line 32, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python2.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/usr/lib/python2.7/calendar.py", line 10, in <module>
    import locale as _locale
  File "/usr/lib/python2.7/locale.py", line 15, in <module>
    import encodings
ImportError: No module named encodings

**Comment by henningpeters** [comment]
This looks like an error with your pip/python installation, this stack trace occurs before any spaCy code is being executed. What version of pip are you running (`pip --version`)? I suspect an outdated version, anything beyond `>=7` is good, `>=8` would be better. Please try to get a new pip (e.g., download and run https://bootstrap.pypa.io/get-pip.py, more instructions at https://pip.pypa.io/en/stable/installing/). Also, you don't need sudo if you install spaCy into a virtualenv (see more info here: https://virtualenv.readthedocs.org/en/latest/). Hope that helps.
