### ISSUE TITLE
Model not installed.

### ISSUE THREAD

**Issue by artemisrj** [spacy-io/spaCy#324]
when  I  run the 
`nlp = spacy.en.English()` or `spacy.load('en')` in the windows with version 0.100.6 
> 
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.1\helpers\pydev\pydevd.py", line 2403, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.1\helpers\pydev\pydevd.py", line 1794, in run
    launch(file, globals, locals)  # execute the script
  File "C:/Users/artemis_zrj/PycharmProjects/sentence_analyse/sub/data_processing/yelp/save_yelp_data.py", line 4, in <module>
    nlp = spacy.en.English()
  File "C:\Users\artemis_zrj\Anaconda2\lib\site-packages\spacy\language.py", line 225, in __init__
    package = util.get_package_by_name()
  File "C:\Users\artemis_zrj\Anaconda2\lib\site-packages\spacy\util.py", line 30, in get_package_by_name
    "model." % name)
RuntimeError: Model None not installed. Please run 'python -m spacy.en.download' to install latest compatible model.
Process finished with exit code 1

But the data is existed in the dir , site-packages\spacy\data\__cache__ \en-1.0.9 ,I tried to download the data again,but it is not useful.

```
>>> import spacy
>>> from spacy.en import English
>>> import sputnik
>>> pkg = sputnik.package(spacy.about.__title__, spacy.about.__version__, 'en')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\artemis_zrj\Anaconda2\lib\site-packages\sputnik\__init__.py", line 160, in package
    return pool.get(package_string)
  File "C:\Users\artemis_zrj\Anaconda2\lib\site-packages\sputnik\package_list.py", line 57, in get
    raise PackageNotFoundException(package_string)
sputnik.package_list.PackageNotFoundException: en
>>> spacy
<module 'spacy' from 'C:\Users\artemis_zrj\Anaconda2\lib\site-packages\spacy\__init__.pyc'>
>>>
```

How can I load the model correctly?

**Comment by henningpeters** [comment]
It looks to me as if the model is not installed. How did you install spacy? Via conda, pip or from source? Also, did you upgrade from a previous version or did you install from scratch?

Did you run `python -m spacy.en.download` and exited successfully? What happens if you run it again?

The directory you are pointing at (`spacy\data__cache__\en-1.0.9`) is a cache directory and might not contain all downloaded data. Please run the following commands and post the output here:

```
python -m sputnik --name spacy find
```

This should print all installed/available models.

```
python -c "import sputnik; print(sputnik.util.default_data_path('spacy'))"
```

This should print the path where the model files are stored on your system.

**Comment by artemisrj** [comment]
I remenber update it with pip,and I forget how it be installed.
I copy the previous version of 0.100.5 and It can run `nlp = spacy.en.English()` but  `spacy.load('en')` can't  find the model too.
I have once run `python -m spacy.en.download` successfully. But when I download it again, it will stop with error, but It maybe the network reason.
Now, with the version of 0.100.5.
`python -m sputnik --name spacy find' with the output
> [
  {
    "name": "en_default",
    "version": "1.0.8"
  }
]

and `python -c "import sputnik; print(sputnik.util.default_data_path('spacy'))" ` with the output:
> C:\Users\artemis_zrj\Anaconda2\lib\site-packages\spacy\data

```
>>> import spacy
>>> spacy.load('en')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\artemis_zrj\Anaconda2\lib\site-packages\spacy\__init__.py", line 6, in load
    package = util.get_package_by_name(name, via=via)
  File "C:\Users\artemis_zrj\Anaconda2\lib\site-packages\spacy\util.py", line 28, in get_package_by_name
    raise RuntimeError("Model not installed. Please run 'python -m "
RuntimeError: Model not installed. Please run 'python -m spacy.en.download' to install latest compatible model.
```

**Comment by henningpeters** [comment]
Sorry, I have a hard time following what you write. By copying the model you might have complicated the situation. I recommend you to try to set it up from scratch again, specifically as you are on anaconda you could try:

```
conda create -n spacy python
source activate spacy
conda install spacy
python -m spacy.en.download
python -c "import spacy; spacy.load('en')"
```

**Comment by artemisrj** [comment]
It works. Thank you.

**Comment by Shylajhaa** [comment]
Error while finding module specification for 'spacy.en.download' (ModuleNotFoundError: No module named 'spacy.en')

I'm getting this error while executing "python -m spacy.en.download:

**Comment by pouyana** [comment]
@Shylajhaa I probably found the solution to this, from [here](http://forums.fast.ai/t/wiki-lesson-4/9402/6):
```
python -m spacy download en
```
should work.

**Comment by stanjin** [comment]
Seeing the following error:

Exception:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Anaconda3\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "C:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "C:\Anaconda3\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\Anaconda3\lib\email\feedparser.py", line 178, in feed
    self._input.push(data)
  File "C:\Anaconda3\lib\email\feedparser.py", line 104, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'
