### ISSUE TITLE
Windows 7 installation issues

### ISSUE THREAD

**Issue by zeluspudding** [spacy-io/spaCy#337]
I've googled around for anyone who's experienced similar issues but haven't found any yet. I thought I successfully installed the English language model 

```
python -m spacy.en.download --force
Downloading...
Downloaded 519.05MB 100.00% 0.24MB/s eta 0s
archive.gz checksum/md5 OK
Model successfully installed.
```
but running `python -c "import spacy; spacy.load('en'); print(u'\U0001F44D')"` results in 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\myUserName\Anaconda2\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
```
I'm at a loss for what to debug next. I'm running windows 7, anaconda 64bit, Can anyone help? Trying to run the example

```
from spacy.en import English
nlp = English()
```
results in sputnik (I believe spaCy's package manager) not being able to load what is I believe the en json
```
Traceback (most recent call last):

  File "<ipython-input-30-cf14a23509cf>", line 2, in <module>
    nlp = English()

  File "C:\Users\myUserName\Anaconda2\lib\site-packages\spacy\language.py", line 225, in __init__
    package = util.get_package_by_name()

  File "C:\Users\myUserName\Anaconda2\lib\site-packages\spacy\util.py", line 26, in get_package_by_name
    name or about.__default_model__, data_path=via)

  File "build\bdist.win-amd64\egg\sputnik\__init__.py", line 159, in package
    pool = Pool(app_name, app_version, expand_path(data_path))

  File "build\bdist.win-amd64\egg\sputnik\pool.py", line 19, in __init__
    super(Pool, self).__init__(app_name, app_version, path, **kwargs)

  File "build\bdist.win-amd64\egg\sputnik\package_list.py", line 33, in __init__
    self.load()

  File "build\bdist.win-amd64\egg\sputnik\package_list.py", line 51, in load
    for package in self.packages():

  File "build\bdist.win-amd64\egg\sputnik\package_list.py", line 47, in packages
    yield self.__class__.package_class(path=os.path.join(self.path, path))

  File "build\bdist.win-amd64\egg\sputnik\package.py", line 14, in __init__

AttributeError: 'NoneType' object has no attribute 'json_load'
```

**Comment by henningpeters** [comment]
Thanks for the report. I think the first one can be easily solved. Just seems to be an encoding issue of the 👍 character. Can you instead please try to run:

```
python -c "import spacy; spacy.load('en'); print('OK')"
```

You say you are running on anaconda, did you also install spaCy via anaconda? Also, which version of Python/spaCy are you using?

**Comment by zeluspudding** [comment]
`python -c "import spacy; spacy.load('en'); print('OK')"` did the trick. I'm running Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]. I *did* install spacy through conda. Here is the version info `spacy                     0.100.6                  py27_0`

**Comment by henningpeters** [comment]
Thanks!

**Comment by zeluspudding** [comment]
Oops, I think there's been a confusion - I should've been more explicit in my previous post. The provided command alternative `python -c "import spacy; spacy.load('en'); print('OK')"` worked for printing out that spacy en installed correctly. However, attempting to load the en module from Python continues to fail at Sputnik with the error previously shown above `AttributeError: 'NoneType' object has no attribute 'json_load'`. Do you have any idea how to resolve this?

**Comment by henningpeters** [comment]
Can you provide me a list of installed packages including version numbers, e.g., with `conda list`? Then I will try to reproduce the `json_load` issue.

**Comment by zeluspudding** [comment]
Sure thing! Thanks for taking a closer look!
```
# packages in environment at C:\Users\myUserName\Anaconda2:
#
alabaster                 0.7.7                    py27_0    defaults
anaconda                  4.0.0               np110py27_0    defaults
anaconda-client           1.4.0                    py27_0    defaults
anaconda-navigator        1.1.0                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astropy                   1.1.2               np110py27_0    defaults
babel                     2.2.0                    py27_0    defaults
backports-abc             0.4                       <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    defaults
beautifulsoup4            4.4.1                    py27_0    defaults
bitarray                  0.8.1                    py27_1    defaults
blaze                     0.9.1                    py27_0    defaults
bokeh                     0.11.1                   py27_0    defaults
boto                      2.39.0                   py27_0    defaults
bottleneck                1.0.0               np110py27_0    defaults
bzip2                     1.0.6                     vc9_2  [vc9]  defaults
cdecimal                  2.3                      py27_1    defaults
cffi                      1.5.2                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
cloudpickle               0.1.1                    py27_0    defaults
clyent                    1.2.1                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
comtypes                  1.1.2                    py27_0    defaults
conda                     4.0.5                    py27_0    defaults
conda-build               1.20.0                   py27_0    defaults
conda-env                 2.4.5                    py27_0    defaults
conda-manager             0.3.1                    py27_0    defaults
configobj                 5.0.6                    py27_0    defaults
console_shortcut          0.1.1                    py27_1    defaults
cryptography              1.3                      py27_0    defaults
curl                      7.45.0                    vc9_1  [vc9]  defaults
cycler                    0.10.0                   py27_0    defaults
cymem                     1.30                     py27_0    spacy
cython                    0.23.4                   py27_0    defaults
cytoolz                   0.7.5                    py27_0    defaults
dask                      0.8.1                    py27_0    defaults
datashape                 0.5.1                    py27_0    defaults
decorator                 4.0.9                    py27_0    defaults
dill                      0.2.4                    py27_0    defaults
docutils                  0.12                     py27_1    defaults
enum34                    1.1.2                    py27_0    defaults
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_0    defaults
flask                     0.10.1                   py27_1    defaults
flask-cors                2.1.2                    py27_0    defaults
freetype                  2.5.5                     vc9_0  [vc9]  defaults
funcsigs                  0.4                      py27_0    defaults
futures                   3.0.3                    py27_0    defaults
gevent                    1.1.0                    py27_0    defaults
greenlet                  0.4.9                    py27_0    defaults
grin                      1.2.1                    py27_2    defaults
h5py                      2.5.0               np110py27_4    defaults
hdf5                      1.8.15.1                  vc9_4  [vc9]  defaults
heapdict                  1.0.0                    py27_0    defaults
idna                      2.0                      py27_0    defaults
ipaddress                 1.0.14                   py27_0    defaults
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.1.2                    py27_1    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jdcal                     1.2                      py27_0    defaults
jedi                      0.9.0                    py27_0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                        vc9_0  [vc9]  defaults
jsonschema                2.4.0                    py27_0    defaults
jupyter                   1.0.0                    py27_2    defaults
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
libpng                    1.6.17                    vc9_1  [vc9]  defaults
libsodium                 1.0.3                         0    defaults
libtiff                   4.0.6                     vc9_1  [vc9]  defaults
llvmlite                  0.9.0                    py27_0    defaults
locket                    0.2.0                    py27_0    defaults
lxml                      3.6.0                    py27_0    defaults
markupsafe                0.23                     py27_1    defaults
matplotlib                1.5.1               np110py27_0    defaults
menuinst                  1.3.2                    py27_0    defaults
mistune                   0.7.2                    py27_0    defaults
mkl                       11.3.1                        0    defaults
mkl-service               1.1.2                    py27_0    defaults
mpmath                    0.19                     py27_0    defaults
multipledispatch          0.4.8                    py27_0    defaults
murmurhash                0.26.2                   py27_0    spacy
nbconvert                 4.1.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2                      py27_0    defaults
nose                      1.3.7                    py27_0    defaults
notebook                  4.1.0                    py27_2    defaults
numba                     0.24.0              np110py27_0    defaults
numexpr                   2.5                 np110py27_0    defaults
numpy                     1.10.4                   py27_0    defaults
odo                       0.4.2                    py27_0    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2g                    vc9_0  [vc9]  defaults
pandas                    0.18.0              np110py27_0    defaults
partd                     0.3.2                    py27_1    defaults
path.py                   8.1.2                    py27_1    defaults
patsy                     0.4.0               np110py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pickleshare               0.5                      py27_0    defaults
pillow                    3.1.1                    py27_0    defaults
pip                       8.1.1                    py27_1    defaults
plac                      0.9.1                    py27_0    defaults
ply                       3.8                      py27_0    defaults
preshed                   0.46.3                   py27_0    spacy
psutil                    4.1.0                    py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycosat                   0.6.1                    py27_0    defaults
pycparser                 2.14                     py27_0    defaults
pycrypto                  2.6.1                    py27_3    defaults
pyflakes                  1.1.0                    py27_0    defaults
pygments                  2.1.1                    py27_0    defaults
pyopenssl                 0.15.1                   py27_2    defaults
pyparsing                 2.0.3                    py27_0    defaults
pyqt                      4.11.4                   py27_5    defaults
pyreadline                2.1                      py27_0    defaults
pytables                  3.2.2               np110py27_2    defaults
pytest                    2.8.5                    py27_0    defaults
python                    2.7.11                        4    defaults
python-dateutil           2.5.1                    py27_0    defaults
pytz                      2016.2                   py27_0    defaults
pywin32                   220                      py27_1    defaults
pyyaml                    3.11                     py27_3    defaults
pyzmq                     15.2.0                   py27_0    defaults
qt                        4.8.7                     vc9_7  [vc9]  defaults
qtawesome                 0.3.2                    py27_0    defaults
qtconsole                 4.2.0                    py27_1    defaults
qtpy                      1.0                      py27_0    defaults
regex                     2016.4.8                  <pip>
requests                  2.9.1                    py27_0    defaults
rope                      0.9.4                    py27_1    defaults
scikit-image              0.12.3              np110py27_0    defaults
scikit-learn              0.17.1              np110py27_0    defaults
scipy                     0.17.0              np110py27_0    defaults
semver                    2.3.1                    py27_0    spacy
setuptools                20.3                     py27_0    defaults
simplegeneric             0.8.1                    py27_0    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.16.9                   py27_2    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.1                    py27_0    defaults
spacy                     0.100.6                  py27_0    spacy
sphinx                    1.3.5                    py27_0    defaults
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py27_0    defaults
sputnik                   0.9.3                    py27_0    spacy
spyder                    2.3.8                    py27_1    defaults
sqlalchemy                1.0.12                   py27_0    defaults
ssl_match_hostname        3.4.0.2                  py27_0    defaults
statsmodels               0.6.1               np110py27_0    defaults
sympy                     1.0                      py27_0    defaults
tables                    3.2.2                     <pip>
thinc                     5.0.7                    py27_0    spacy
tk                        8.5.18                    vc9_0  [vc9]  defaults
toolz                     0.7.4                    py27_0    defaults
tornado                   4.3                      py27_0    defaults
traitlets                 4.2.1                    py27_0    defaults
ujson                     1.35                     py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
vs2008_runtime            9.00.30729.1                  0    defaults
vs2010_runtime            10.00.40219.1                 0    defaults
werkzeug                  0.11.4                   py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
xlrd                      0.9.4                    py27_0    defaults
xlsxwriter                0.8.4                    py27_0    defaults
xlwings                   0.7.0                    py27_0    defaults
xlwt                      1.0.0                    py27_0    defaults
zlib                      1.2.8                     vc9_2  [vc9]  defaults
```

**Comment by henningpeters** [comment]
I have following theory: your sputnik version is outdated/incompatible. The one listed with `conda list` indicates that it is not, but if you look carefully at the paths in your stack trace the called sputnik functions are not from the conda install:

```
build\bdist.win-amd64\egg\sputnik\__init__.py
build\bdist.win-amd64\egg\sputnik\pool.py
build\bdist.win-amd64\egg\sputnik\package_list.py
```

Do you have any idea how this install might creep into your conda environment? I am sure that once you have your conda sputnik running the problem will disappear.

**Comment by zeluspudding** [comment]
That's an interesting theory - I'm not sure how that could be. I've had a need to run both 32bit and 64bit anaconda so my best guess is perhaps installing to an incorrect directory + currently existing system path precedence has something to do with it. I feel that's a poor guess, though. I will uninstall sputnik then reinstall then see what happens

**Comment by zeluspudding** [comment]
Well... darn. I've attempted uninstalling, reinstalling, clearing any pip installations that may have existed for sputnik and still get the same problem. Any suggestions beyond nuking anaconda / python installations and recreating my environment?

**Comment by zeluspudding** [comment]
What parent directory would let me access 
```
build\bdist.win-amd64\egg\sputnik\__init__.py
build\bdist.win-amd64\egg\sputnik\pool.py
build\bdist.win-amd64\egg\sputnik\package_list.py
```
to delete them?

**Comment by henningpeters** [comment]
Is there a `build` directory in your current working directory? If yes, try to get rid of it.

**Comment by zeluspudding** [comment]
Deleted `C:\Users\MyUserName\Anaconda2\Lib\site-packages\Cython\Build`. That didn't solve the issue. I completely reinstalled anaconda2 and SpaCy and the problem persists.

**Comment by henningpeters** [comment]
Try searching your PYTHONPATH and your system for the files. They must be somewhere...
