### ISSUE TITLE
Permission Error when calling English()

### ISSUE THREAD

**Issue by jtexnl** [spacy-io/spaCy#349]
I've recently been having this problem whenever I try to use spaCy. It was working fine previously, so I'm not sure if the change has to do with versions or if I've changed something in my permissions. Is this an issue on spaCy's end or on my end?
``` 
>>> from spacy.en import English
>>> parser = English()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/spacy/language.py", line 225, in __init__
    package = util.get_package_by_name()
  File "/usr/local/lib/python3.4/site-packages/spacy/util.py", line 26, in get_package_by_name
    name or about.__default_model__, data_path=via)
  File "/usr/local/lib/python3.4/site-packages/sputnik/__init__.py", line 159, in package
    pool = Pool(app_name, app_version, expand_path(data_path))
  File "/usr/local/lib/python3.4/site-packages/sputnik/pool.py", line 19, in __init__
    super(Pool, self).__init__(app_name, app_version, path, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/sputnik/package_list.py", line 33, in __init__
    self.load()
  File "/usr/local/lib/python3.4/site-packages/sputnik/package_list.py", line 51, in load
    for package in self.packages():
  File "/usr/local/lib/python3.4/site-packages/sputnik/package_list.py", line 37, in packages
    os.makedirs(self.path)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/site-packages/spacy/data' 
```

**Comment by jtexnl** [comment]
Never mind, I think I've figured it out. Looks like it was on my end, not spaCy's.

**Comment by PratimaVK** [comment]
Hi. I am getting similar error. May I know how did you solve it?

C:\WINDOWS\system32>python -m spacy.en.download
archive.gz checksum/md5 OK
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\PratimaK\AppData\Roaming\Python\Python34\site-packages\spacy\en\download.py", line 13, in <module>
    plac.call(main)
  File "C:\Users\PratimaK\AppData\Roaming\Python\Python34\site-packages\plac_core.py", line 324, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "C:\Users\PratimaK\AppData\Roaming\Python\Python34\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\PratimaK\AppData\Roaming\Python\Python34\site-packages\spacy\en\download.py", line 9, in main
    download('en', force)
  File "C:\Users\PratimaK\AppData\Roaming\Python\Python34\site-packages\spacy\download.py", line 24, in download
    package = sputnik.install(about.__title__, about.__version__, about.__models__[lang])
  File "C:\Python34\lib\site-packages\sputnik\__init__.py", line 46, in install
    path = pool.install(archive)
  File "C:\Python34\lib\site-packages\sputnik\pool.py", line 47, in install
    os.rename(path + '.tmp', path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\PratimaK\\AppData\\Roaming\\Python\\Python34\\site-packages\\spacy\\data\\en-1.1.0.tmp' -> 'C:\\Users\\PratimaK\\AppData\\Roaming\\Python\\Python34\\site-packages\\spacy\\data\\en-1.1.0'

**Comment by jtexnl** [comment]
Honestly, at this point I can't remember what my fix was. I remember I had to adjust something with my path variables through an export command, but I was working from a Linux instance; not sure how I would go about it in a Windows environment.

**Comment by Thembani-p** [comment]
@PratimaVK I had the same problem. I think it comes down to the following file and line of code

* File "C:\Python34\lib\site-packages\sputnik\pool.py", line 47, in install 
* os.rename(path + '.tmp', path)

I looked at the file system folders under 'spacy/data/' you will find a folder called '__cache__' and another one corresponding to your language model, in this case 'en-1.1.0 .tmp'

I don't have a for the error. That said, I removed the '.tmp' from the folder name and used spacy.en and it worked. As far as I can tell the content of 'en-1.1.0' are the same as in another installation that I have.

**Comment by evanmiltenburg** [comment]
I had the same issue (even though I was running the download command in administrator mode), and renaming `en-1.1.0.tmp` to `en-1.1.0` worked! So somehow the permissions should be changed, such that the renaming operation is allowed.

**Comment by evanmiltenburg** [comment]
I had the same issue (even though I was running the download command in administrator mode), and renaming `en-1.1.0.tmp` to `en-1.1.0` worked! So somehow the permissions should be changed, such that the renaming operation is allowed.

**Comment by yooper** [comment]
@evanmiltenburg, your solution worked for me.

**Comment by evanmiltenburg** [comment]
Perhaps this issue should be reopened, if more people run into this issue.
