### ISSUE TITLE
Could not sucessfully download language model

### ISSUE THREAD

**Issue by pwichmann** [spacy-io/spaCy#356]
Could not successfully download language model:

Last login: Sun May  1 22:42:43 on ttys002
Pascals-MacBook-Pro:~ pascalwichmann$ python -m spacy.en.download
Traceback (most recent call last):
  File "/Users/pascalwichmann/anaconda/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/Users/pascalwichmann/anaconda/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/Users/pascalwichmann/anaconda/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/Users/pascalwichmann/anaconda/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/Users/pascalwichmann/anaconda/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/Users/pascalwichmann/anaconda/lib/python2.7/site-packages/spacy/__init__.py", line 2, in <module>
    from .en import English
  File "/Users/pascalwichmann/anaconda/lib/python2.7/site-packages/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/Users/pascalwichmann/anaconda/lib/python2.7/site-packages/spacy/language.py", line 11, in <module>
    from .tokenizer import Tokenizer
  File ".env/local/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd", line 155, in init spacy.tokenizer (spacy/tokenizer.cpp:10076)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by pwichmann** [comment]
The problem was an outdated NumPy version.

**Comment by henningpeters** [comment]
Which numpy version did you originally have an to which did you upgrade to? This info would help us validating our assumptions on numpy compatibility.

**Comment by pwichmann** [comment]
Hi Henning,
Sure! I could reconstruct which version I had before:
I upgraded from numpy 1.9.2 to numpy-1.11.0.
It was my secondary machine so numpy was quite outdated.

(Also, I have posted a question on the spacy reddit ;) )

**Comment by henningpeters** [comment]
Perfect, thanks! Current spaCy requires `numpy>=1.10`. Future spaCy versions will be compatible with `numpy>=1.7` as there is actually no reason not be a bit more backwards-compatible.

**Comment by henningpeters** [comment]
We just made a new release (0.100.7). you can now install spaCy along numpy 1.9 or any other `numpy>=1.7` release.
