### ISSUE TITLE
AssertionError (in Tokeinzer?) since v0.100.7

### ISSUE THREAD

**Issue by bwegge** [spacy-io/spaCy#360]
Hi, I really like spaCy, but I just stumbled across an an AssertionError after upgrading to v0.100.7 (from v0.100.6):

```
nlp(newsgroups_train.data[830])
Traceback (most recent call last):

  File "<ipython-input-20-bb7a87e9e11a>", line 1, in <module>
    nlp(newsgroups_train.data[830])

  File "C:\Users\bwegge\AppData\Local\Continuum\Anaconda3\lib\site-packages\spacy\language.py", line 225, in __call__
    tokens = self.tokenizer(text)

  File "spacy/tokenizer.pyx", line 118, in spacy.tokenizer.Tokenizer.__call__ (spacy/tokenizer.cpp:4664)

  File "spacy/tokenizer.pyx", line 159, in spacy.tokenizer.Tokenizer._tokenize (spacy/tokenizer.cpp:5409)

  File "spacy/tokenizer.pyx", line 231, in spacy.tokenizer.Tokenizer._attach_tokens (spacy/tokenizer.cpp:6444)

  File "spacy/tokens/doc.pyx", line 282, in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:8356)

AssertionError


newsgroups_train.data[830]
'Misc. Items for sale:\n\n\nMount Plate:  Sony Model CPM-203P, mounting plate for Sony portable CD players\nfor Portable: plugs into car lighter, snaps onto the bottom of any Sony\nCD Player:    Portable CD player, perfect condition. Will also throw in a \n\t      cassette adapter in SO SO condition.\n\t      Paid $45...............Asking $30.\n\nCar Speakers:\tSherwood 5 1/4" two way car speakers, in car for 7 months,\n5 1/4 inch:\texcellent condition, Paid $65............Asking $40.\n\n4 inch:\t    Factory Speakers from Toyota excellent condition Asking $20.\n\n\nNintendo:   Nintendo Game Boy, Light Boy, Tetris, Super Mario Land,  \nGameboy:    NFL Football, Castlevania Adventure, Hyper Lode Runner, 4 years\n+ games:    old\tall in working condition, Asking $70.\nAccessories:\n\n\nWhole Internet:\tThe Whole Internet: User\'s Guide and Catalog by ED Krol,\nbook:\t\tguide to using the internet, where to fing information and \n\t\tresources.   Paid $30..........Asking $20.\n\nMicroSoft:    Never Used, came with my computer, Asking $30.\nVisual Basic:\n\nMicroSoft: \t   Came with my computer, never used, Asking $100.\nWord for Windows:\n\n\n\t\t\t\t\tThanks,'
```

**Comment by honnibal** [comment]
Thanks, will look into this.

**Comment by kedarbellare** [comment]
The problem occurs due to the consecutive series of dots:
>>> nlp(u'Paid $45...............Asking $30')
AssertionError: 
assert t.lex.orth != 0

I was able to solve the problem by putting spaces around the dots. 
>>> nlp(re.sub(r'(\.{2,})', r' \1 ', u'Paid $45...............Asking $30'))

**Comment by honnibal** [comment]
Thanks for the minimal test case.

The proximate cause here is that the tokenizer doesn't handle longer ellipses correctly. That's easily fixed --- one of the regular expressions just needed a little tweak. But, obviously no string should be an error!

The problem was introduced when I adjusted the tokenizer to handle strings with multiple "infix" separators, so that strings like "Yeah...okay...I...see" would be tokenized correctly. The problem should be fixed now.
