### ISSUE TITLE
Install error under Max OSX: no module named linear.avgtron

### ISSUE THREAD

**Issue by phdowling** [spacy-io/spaCy#393]
I'm struggling to get spacy running on my macbook, something seems to go wrong with installing the thinc dependency:

```
$ conda install spacy
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/dowling/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.0.6                |           py27_0         185 KB
    preshed-0.46.4             |           py27_0          54 KB
    thinc-5.0.8                |           py27_0         320 KB
    spacy-0.100.7              |           py27_0         1.3 MB
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

    spacy:   0.100.7-py27_0
    thinc:   5.0.8-py27_0  

The following packages will be UPDATED:

    conda:   4.0.5-py27_0  --> 4.0.6-py27_0  
    preshed: 0.46.2-py27_0 --> 0.46.4-py27_0 

Proceed ([y]/n)? y

Fetching packages ...
conda-4.0.6-py 100% |################################################################################################################################################################################################################################| Time: 0:00:00 259.16 kB/s
preshed-0.46.4 100% |################################################################################################################################################################################################################################| Time: 0:00:00 226.69 kB/s
thinc-5.0.8-py 100% |################################################################################################################################################################################################################################| Time: 0:00:01 196.77 kB/s
spacy-0.100.7- 100% |################################################################################################################################################################################################################################| Time: 0:00:01   1.26 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################################################################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################################################################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################################################################################################################################################################################################################| 100%
$ python
Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dowling/anaconda/lib/python2.7/site-packages/spacy/__init__.py", line 3, in <module>
    from . import en
  File "/Users/dowling/anaconda/lib/python2.7/site-packages/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/Users/dowling/anaconda/lib/python2.7/site-packages/spacy/language.py", line 13, in <module>
    from .syntax.parser import Parser
  File "spacy/syntax/parser.pyx", line 1, in init spacy.syntax.parser (spacy/syntax/parser.cpp:21179)
ImportError: No module named linear.avgtron
>>> 
$ python -m spacy.en.download
/Users/dowling/anaconda/bin/python: No module named linear.avgtron
```

Any clue how to fix this? everything seems to install fine, but spacy can't be imported.

**Comment by geovedi** [comment]
I see you have slightly old version of Anaconda. Can you try to update it first? As I have no problem with current Anaconda version, `Anaconda2-4.0.0`.

**Comment by phdowling** [comment]
I've just updated anaconda, but unfortunately the error persists.

**Comment by phdowling** [comment]
Did a `conda clean --all` and a bunch of pip removes, etc. Anyway, that effective hard-reset followed by a reinstall of spacy seems to have fixed this.
