### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RahulKulhari** [spacy-io/spaCy#421]
**While Downloading data getting this error**

`python -m spacy.en.download`

**Error:**

```

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "//anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/anaconda/lib/python2.7/site-packages/spacy/en/download.py", line 1, in <module>
    import plac
  File "//anaconda/lib/python2.7/site-packages/plac.py", line 38, in <module>
    from plac_tk import TkMonitor
  File "//anaconda/lib/python2.7/site-packages/plac_tk.py", line 46
    print('Process %d killed by CTRL-C' % os.getpid(), file=sys.stderr)
                                                           ^
SyntaxError: invalid syntax
```
I installed plac v 0.9.3

Can any one help me please ?

**Comment by RahulKulhari** [comment]
installed plac 0.9.2 and it got solved
