### ISSUE TITLE
Setup on windows :ImportError: No module named 'spacy.attrs'

### ISSUE THREAD

**Issue by patilvish1** [spacy-io/spaCy#510]
Hi 
 I tried to setup the code on windows 7 professional version with 64 bit.
 
 I used chocolatey to install python  and then use following steps in command prompt

     cd <sourcecode directory>
     python -m pip install -U pip virtualenv
     git clone https://github.com/spacy-io/spaCy.git
          
     #activate .env
     virtualenv .env
     .env\Scripts\activate

     cd spaCy
     pip install -r requirements.txt

     pip install spaCy
     
     #install model
     sputnik --name spacy --repository-url http://index.spacy.io install en==1.1.0

     python -c "import spacy; spacy.load('en'); print('OK')"

However i am getting error  "ImportError: No module named 'spacy.attrs' "

Details
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\spacy.io\code\test\spaCy\spacy\__init__.py", line 3, in <module>
    from .util import set_lang_class, get_lang_class
  File "D:\spacy.io\code\test\spaCy\spacy\util.py", line 9, in <module>
    from .attrs import TAG, HEAD, DEP, ENT_IOB, ENT_TYPE
    ImportError: No module named 'spacy.attrs'

what am i missing ?

Also, does anyone know steps to open this project in visual studio 2015?
Vishal

**Comment by patilvish1** [comment]
Figured out I forgot  "pip install e."
For anyone who is interested in setting up this on windows ( I used win 7 with 64 bit), here are steps 


a. Goto command line (open in admin previlliages ) and run following to install Chocolatey

@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object 

System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH

%;%ALLUSERSPROFILE%\chocolatey\bin"




b. Use Chocolatey To install python :  It installs in C:\ProgramData\chocolatey\lib\python3
cinst python

c. Create a source directory for spacy code and then 
cd <sourcecode directory>

d. Setup virtual environment framework
python -m pip install -U pip virtualenv
 

e. Get git code
git clone https://github.com/spacy-io/spaCy.git


f. setup virutal enviornment name .env
virtualenv .env

g. activate .env and run remaining instllation steps of spacy
           .env\Scripts\activate
           cd spaCy
           pip install -r requirements.txt
           pip install spaCy
           sputnik --name spacy --repository-url http://index.spacy.io install en==1.1.0
           pip install -e .


 h. check success to see 'OK'
       python -c "import spacy; spacy.load('en'); print('OK')"

###########################
I still need to figure out how to open this project in VS 2015. 

In case anyone knows it, please let me know.
